### ISSUE TITLE
TestLink does not work with HTTPS?

### ISSUE THREAD

**Issue by cryzeSVK** [TestLinkOpenSourceTRMS/testlink-documentation#3]
Hello,

I am trying to get TestLink work on our local server using HTTPS instead of HTTP.
The Application is installed without problem but after login (admin/admin) the page is blank. Console shows multiples errors of "Mixed Content" type. Basically the page does not show anything because it requests resources using HTTP link instead of HTTPS.

Is there any way how to solve this or the code has to be rewritten ? Thanks.

**Comment by fmancardi** [comment]
Hi
please use forum for ask for config issues or open an issue on mantis
